name: qAlice-Py313
channels:
  - conda-forge
channel_priority: strict
solver: libmamba
dependencies:
  - python=3.13
  - pip
  - numpy>=1.24.0
  - pandas>=2.3.0
  - scikit-learn>=1.7.0
  - scipy
  - networkx
  - pyarrow>=12.0.0
  - typer>=0.17.0
  - pytest>=8.0
  - pytest-cov>=7.0.0
  - black>=23.0.0
  - flake8>=6.0.0
  - ruff
  - isort
  - pre-commit>=3.0.0
  - psutil
