# mamba env update --prune -f environment.yml
name: qAlice-Py313
channels:
  - conda-forge
channel_priority: strict
solver: libmamba
dependencies:
  - pip
  - pip:
      - pyqubo
      - dimod
      - openjij
      - dwave-ocean-sdk
      - qiskit
