name: Build qAlice
run-name: ${{ github.actor }} is building qAlice

on:
    workflow_dispatch: ~
    push:
        branches: [ '**' ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -e .
      - name: Lint
        run: |
          ruff check .
          black --check .
          isort --check-only .
      - name: Tests
        run: |
          pytest -q
